### ISSUE TITLE
Lava lamp has no effective tool, chandelier doesn't drop when mined

### ISSUE THREAD

**Issue by GeneralBug** [Artienia80/RubinatedNether#11]
Lava lamp has no effective tool so it can't be picked back up and takes ages to mine. The chandelier doesn't drop when mined, though it does drop when it falls from the ceiling.

Also the freezer recipes don't appear in EMI but I'm guessing that's already planned

**Comment by serenyadev** [comment]
Freezer recipes not appearing in EMI is weird, integration has already been made and they appear just fine on my machine. The drops is due to a datagen mistake and will be fixed in a hotfix release.

**Comment by GeneralBug** [comment]
I figured out the EMI thing, I was trying to check the uses of the freezer directly but the recipes do show up when checking the ingredients/products.

**Comment by Artienia80** [comment]
Hello GeneralBugy I am Artienia, author of RN.

We are working on this critical bug immediately and will be releasing v1.1.1b fixing this issue later today.

Thank you for your patience

**Comment by Artienia80** [comment]
Fixed in v1.1.1b
