### ISSUE TITLE
Freezer Crash

### ISSUE THREAD

**Issue by pafeuu** [Artienia80/RubinatedNether#12]
Forge 1.20.1
RubinatedNether 1.1.1b

Opening freezer gui instantly crashes the game
[latest.log](https://github.com/user-attachments/files/17166113/latest.log)
[crash-2024-09-27_17.02.33-client.txt](https://github.com/user-attachments/files/17166115/crash-2024-09-27_17.02.33-client.txt)

**Comment by Artienia80** [comment]
We are working on an emergency hotfix.

Thank you for your patience.

**Comment by Artienia80** [comment]
Fixed in v1.1.2
