### ISSUE TITLE
Immersive Weathering compat recipes

### ISSUE THREAD

**Issue by pafeuu** [Artienia80/RubinatedNether#16]
[Immersive_weathering.zip](https://github.com/user-attachments/files/17173836/Immersive_weathering.zip)
Hi I wanted to add those recipes for my modpack anyway. Maybe you can use them in an actual mod

**Comment by pafeuu** [comment]
Nevermind, my confidence deceived me. There were tons of typos in there. Working file:
[immersive_weathering.zip](https://github.com/user-attachments/files/17173882/immersive_weathering.zip)

**Comment by Artienia80** [comment]
Implemented in 1.3.0.D
