### ISSUE TITLE
Ruby Lens overlay opaque

### ISSUE THREAD

**Issue by Screamermod** [Artienia80/RubinatedNether#25]
When I put on Ruby Lenses, they obscure my vision. Going into third person shows they still show lasers correctly, just the overlay is broken.
![image](https://github.com/user-attachments/assets/4b0f3f11-e337-4b84-a1fb-71f7e8aa20b4)

**Comment by Artienia80** [comment]
This happens on FAST graphics i believe. Are you using Forge or Fabric as the modloader?

**Comment by Artienia80** [comment]
This must have something to do with translucency, currently it works fine on our closed build of V1.2.0.

When that version releases this week, please tell us if the issue has resolved itself or not! Thank you

**Comment by Artienia80** [comment]
This bug should now be fixed on v1.2.0

**Comment by Snowy893** [comment]
This happens to me as well, 1.20.1 forge. The orange parts look opaque on fancy graphics, and completely clear on fast.

**Comment by darksonic300** [comment]
Which mod version are you running?
