### ISSUE TITLE
Create: Estrogen incompatibility

### ISSUE THREAD

**Issue by AlokinWolffe** [Artienia80/RubinatedNether#32]
_**Somehow**_ causes the Create: Estrogen mod to not load correctly

Modlist is only Estrogen + Dependencies + Rubinated Nether
Forge 1.20.1
Create 0.5.1.j
Create: Estrogen 4.3.1
Botarium 2.3.4
Resourceful Lib 2.1.29
Rubinated Nether 1.2.0

Causes certain functions to be unable to be loaded:
uwu.serenity.critter.api.AbstractRegistrar

**Comment by Artienia80** [comment]
This will be investigated immediately

**Comment by serenyadev** [comment]
can you send the crash log?

**Comment by AlokinWolffe** [comment]
> can you send the crash log?

[---- Minecraft Crash Report ----.txt](https://github.com/user-attachments/files/17908040/----.Minecraft.Crash.Report.----.txt)
